### ISSUE TITLE
[Template] New Project Proposal

### ISSUE THREAD

**Issue by wuchong** [flink-extended/incubator#1]
# Repository Name
Short and memorable name of this new project. 

Examples: 

> flink-remote-shuffle

# Description
A short descriptive summary of the project. A short paragraph, ideally one sentence in length. 

Examples (ai-flow):
> AI Flow is an open source framework that bridges big data and artificial intelligence.

# Proposal
A lengthier description of the proposal. Should be reasonably declarative. More discursive material should be included in the rationale.

Example (ai-flow):
> AIFlow is an open source framework that bridges big data and artificial intelligence. It manages the entire machine learning lifecycle as a unified workflow, including feature engineering, model training, model evaluation, model service, model inference, monitoring, etc.
> 
> In addition to the capability of orchestrating a group of batch jobs, by leveraging an event-based scheduler(enhanced version of Apache Airflow), AIFlow also supports workflows that contain streaming jobs. Such capability is quite useful for complicated real-time machine learning systems as well as other real-time workflows.

# Documentation
References to further reading material.

Examples (ai-flow):
> Information on AIFlow can be found at: https://ai-flow.readthedocs.io

# Initial Source
Describes the origin of the proposed code base. If the initial code arrives from more than one source, this is the right place to outline the different histories.

If there is no initial source, please describe the current status of the proposed code base. 

Example (flink-cdc):
> The initial source code for flink-cdc is hosted at https://github.com/ververica/flink-cdc-connectors.

# Project Admin
List of admins (stating name and GitHub ID) used to bootstrap the community. The admin have the permission to read, clone, and push to this repository, can also manage issues, pull requests, and repository settings, including adding collaborators.

Example:

> Jark Wu (wuchong)
> Jiangjie Qin (becketqin)

**Comment by novakov-alexey** [comment]
@wuchong is it possible to reuse this template somehow? Can you share markdown text of it?

**Comment by wuchong** [comment]
@novakov-alexey good point! I have moved the template as a source code in the repository and updated the README to link to the markdown file. I will close this template issue then.
